#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# audit-ecc.sh
# opencode-power-kit v1.8.0
#
# Read-only ECC audit tool. Clones ECC to .tmp/ecc/, runs a
# structured audit, creates docs/ECC_AUDIT.md, then removes the
# clone. Never modifies ECC, never installs ECC globally, never
# touches .env / secrets / MCP config.
#
# ECC is a separate, third-party project (see THIRD_PARTY.md):
#   https://github.com/affaan-m/ECC
# ─────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_ECC="${KIT_DIR}/.tmp/ecc"
ECC_REPO="https://github.com/affaan-m/ECC.git"
AUDIT_OUTPUT="${KIT_DIR}/docs/ECC_AUDIT.md"
MODE="interactive"

# ─── Usage ────────────────────────────────────────────────────────
usage() {
	cat <<EOF
Usage: ${SCRIPT_NAME} [--dry-run] [--yes]

Read-only audit of Engineering Code Commandments (ECC).

FLAGS:
  --dry-run        Print the plan. Do not clone or audit.
  --yes            Skip the confirmation prompt. Run audit immediately.
  -h, --help       Show this help.

DETAILS:
  - Clones ECC to .tmp/ecc/ (git clone --depth 1).
  - Analyzes: directory structure, commandments, scripts, hooks.
  - Generates docs/ECC_AUDIT.md with structured findings.
  - Removes .tmp/ecc/ after audit completes.
  - NEVER modifies ECC on disk or globally.
  - NEVER touches .env, secrets, or MCP configuration.

EXAMPLES:
  ${SCRIPT_NAME} --dry-run
  ${SCRIPT_NAME} --yes
EOF
}

# ─── Argument parsing ─────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
	case "$1" in
	--dry-run)
		MODE="dry-run"
		shift
		;;
	--yes)
		MODE="yes"
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "ERROR: unknown option: $1" >&2
		usage >&2
		exit 2
		;;
	esac
done

# ─── Pre-flight ───────────────────────────────────────────────────
if ! command -v git >/dev/null 2>&1; then
	echo "ERROR: 'git' is not on PATH." >&2
	exit 1
fi

echo "=== audit-ecc ==="
echo "Mode:        ${MODE}"
echo "ECC repo:    ${ECC_REPO}"
echo "Temp dir:    ${TMP_ECC}"
echo "Audit out:   ${AUDIT_OUTPUT}"
echo ""

# ─── Dry run ──────────────────────────────────────────────────────
if [[ "${MODE}" == "dry-run" ]]; then
	echo "Plan:"
	echo "  1. git clone --depth 1 ${ECC_REPO} → ${TMP_ECC}"
	echo "  2. Analyze ECC structure and commandments"
	echo "  3. Write audit report to ${AUDIT_OUTPUT}"
	echo "  4. Remove ${TMP_ECC}/"
	echo ""
	echo "Dry run complete. Re-run with --yes to audit."
	exit 0
fi

# ─── Interactive confirmation ─────────────────────────────────────
if [[ "${MODE}" == "interactive" ]]; then
	if [[ ! -t 0 ]]; then
		echo "ERROR: no TTY available; refusing to run without --yes." >&2
		exit 1
	fi
	read -r -p "Clone ECC to .tmp/ecc/ and run audit? [y/N] " reply
	case "${reply}" in
	y | Y | yes | YES) : ;;
	*)
		echo "aborted."
		exit 0
		;;
	esac
fi

# ─── Phase 1: Clone ECC ───────────────────────────────────────────
echo "==> [1/4] Clone ECC (depth 1)..."
mkdir -p "${KIT_DIR}/.tmp"
if [[ -d "${TMP_ECC}" ]]; then
	echo "  Removing previous clone at ${TMP_ECC}"
	rm -rf "${TMP_ECC}"
fi
git clone --depth 1 "${ECC_REPO}" "${TMP_ECC}" 2>&1 | tail -3
echo "  ✅ Cloned to ${TMP_ECC}"
echo ""

# ─── Phase 2: Analyze ECC structure ───────────────────────────────
echo "==> [2/4] Analyze ECC structure..."
ECC_VERSION=""
if [[ -f "${TMP_ECC}/VERSION" ]]; then
	ECC_VERSION="$(tr -d '[:space:]' <"${TMP_ECC}/VERSION")"
elif [[ -f "${TMP_ECC}/package.json" ]]; then
	ECC_VERSION="$(grep -o '"version": *"[^"]*"' "${TMP_ECC}/package.json" 2>/dev/null | head -1 | cut -d'"' -f4)"
fi
ECC_VERSION="${ECC_VERSION:-unknown}"

# Count files/dirs
ECC_FILE_COUNT="$(find "${TMP_ECC}" -type f 2>/dev/null | wc -l)"
ECC_DIR_COUNT="$(find "${TMP_ECC}" -type d 2>/dev/null | wc -l)"
ECC_SCRIPT_COUNT="$(find "${TMP_ECC}" -name '*.sh' -o -name '*.bash' 2>/dev/null | wc -l)"
ECC_MD_COUNT="$(find "${TMP_ECC}" -name '*.md' 2>/dev/null | wc -l)"
ECC_HOOK_COUNT="$(find "${TMP_ECC}" -path '*/hooks/*' -type f 2>/dev/null | wc -l)"

# Top-level structure
TOP_LEVEL="$(ls -1 "${TMP_ECC}" 2>/dev/null)"

echo "  Version:     ${ECC_VERSION}"
echo "  Files:       ${ECC_FILE_COUNT}"
echo "  Dirs:        ${ECC_DIR_COUNT}"
echo "  Scripts:     ${ECC_SCRIPT_COUNT}"
echo "  Markdown:    ${ECC_MD_COUNT}"
echo "  Hooks:       ${ECC_HOOK_COUNT}"
echo ""

# ─── Phase 3: Write audit report ─────────────────────────────────
echo "==> [3/4] Write audit report to ${AUDIT_OUTPUT}..."

mkdir -p "${KIT_DIR}/docs"

cat >"${AUDIT_OUTPUT}" <<EOFAUDIT
# ECC Audit Report

> Generated by \`audit-ecc.sh\` on $(date '+%Y-%m-%d %H:%M:%S')
> Read-only audit — no ECC assets were modified or installed.

## Overview

| Attribute | Value |
|-----------|-------|
| **Project** | Engineering Code Commandments (ECC) |
| **Repository** | https://github.com/affaan-m/ECC |
| **Audited version** | ${ECC_VERSION} |
| **Total files** | ${ECC_FILE_COUNT} |
| **Total directories** | ${ECC_DIR_COUNT} |
| **Shell scripts** | ${ECC_SCRIPT_COUNT} |
| **Markdown files** | ${ECC_MD_COUNT} |
| **Hook files** | ${ECC_HOOK_COUNT} |

## Top-Level Structure

\`\`\`
${TOP_LEVEL}
\`\`\`

## Key Commandments (from ECC)

EOFAUDIT

# Extract key commandments from ECC files
if [[ -d "${TMP_ECC}" ]]; then
	# Look for commandment definitions in markdown files
	find "${TMP_ECC}" -maxdepth 3 -name '*.md' -type f 2>/dev/null | while read -r md; do
		rel="${md#"${TMP_ECC}"/}"
		# Extract headings as potential commandments
		headings="$(grep -E '^#{1,3}\s+' "$md" 2>/dev/null | head -20 || true)"
		if [[ -n "${headings}" ]]; then
			{
				echo ""
				echo "### ${rel}"
				echo "${headings}"
			} >>"${AUDIT_OUTPUT}"
		fi
	done
fi

{
	echo ""
	echo "---"
	echo ""
	echo "## ECC-lite Integration Notes"
	echo ""
	echo "The following ECC principles are relevant to OPK's ECC-lite integration:"
	echo ""
	echo "1. **Research-first** — Understand before implementing"
	echo "2. **Quality gate** — Verify before merging"
	echo "3. **Verification loop** — Test after every change"
	echo "4. **Assumption checking** — Surface implicit assumptions"
	echo '5. **Test-before-done** — No "done" without a passing test'
	echo "6. **Security/reliability review** — Systematic review gates"
	echo ""
	echo "These are available as OPK slash commands. See \`ECC_INTEGRATION.md\`."
} >>"${AUDIT_OUTPUT}"

echo "  ✅ Audit report written (${AUDIT_OUTPUT})"
echo ""

# ─── Phase 4: Cleanup ─────────────────────────────────────────────
echo "==> [4/4] Cleanup ECC clone..."
rm -rf "${TMP_ECC}"
echo "  ✅ Removed ${TMP_ECC}/"
echo ""

echo "🎉 ECC audit complete."
echo "   Report: ${AUDIT_OUTPUT}"
