#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# hermes-learning-capsule.sh
# opencode-power-kit v1.9.0
#
# Package learnings from .hermes/learnings/ into a structured
# capsule report. Read-only — never modifies source learnings.
# ─────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LEARNINGS_DIR="${KIT_DIR}/.hermes/learnings"
OUTPUT_FILE=""
MODE="interactive"

# ─── Usage ────────────────────────────────────────────────────────
usage() {
	cat <<EOF
Usage: ${SCRIPT_NAME} [--dry-run] [--yes] [--output FILE]

Package .hermes/learnings/ into a structured capsule report.

FLAGS:
  --dry-run        Print the plan. Do not package.
  --yes            Skip the confirmation prompt.
  --output FILE    Write capsule to FILE (default: stdout).
  -h, --help       Show this help.

DETAILS:
  - Scans .hermes/learnings/ for all .md files.
  - Compiles them into a structured capsule report.
  - Groups by date, topic, and type (retro vs learning).
  - NEVER modifies source learning files.
  - If .hermes/learnings/ does not exist, shows info message.

EXAMPLES:
  ${SCRIPT_NAME}
  ${SCRIPT_NAME} --output docs/HERMES_LEARNING_CAPSULE.md
  ${SCRIPT_NAME} --dry-run
EOF
}

# ─── Argument parsing ─────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
	case "$1" in
	--dry-run)
		MODE="dry-run"
		shift
		;;
	--yes)
		MODE="yes"
		shift
		;;
	--output)
		if [[ -z "${2:-}" ]]; then
			echo "ERROR: --output requires a file argument" >&2
			exit 2
		fi
		OUTPUT_FILE="$2"
		shift 2
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "ERROR: unknown option: $1" >&2
		usage >&2
		exit 2
		;;
	esac
done

# ─── Pre-flight ───────────────────────────────────────────────────
echo "=== hermes-learning-capsule ==="

# ─── Dry run ──────────────────────────────────────────────────────
if [[ "${MODE}" == "dry-run" ]]; then
	echo "Mode: dry-run"
	if [[ ! -d "${LEARNINGS_DIR}" ]]; then
		echo "ℹ️  No .hermes/learnings/ directory found."
		echo "   Nothing to package."
	else
		COUNT="$(find "${LEARNINGS_DIR}" -name '*.md' -type f 2>/dev/null | wc -l)"
		echo "Learnings found: ${COUNT}"
		echo "Output: ${OUTPUT_FILE:-stdout}"
		echo ""
		echo "Plan:"
		echo "  1. Read all .md files from ${LEARNINGS_DIR}"
		echo "  2. Group by date and topic"
		echo "  3. Generate structured capsule"
	fi
	echo ""
	echo "Dry run complete. Re-run without --dry-run to package."
	exit 0
fi

# ─── Check if learnings exist ─────────────────────────────────────
if [[ ! -d "${LEARNINGS_DIR}" ]]; then
	echo "ℹ️  No .hermes/learnings/ directory found."
	echo "   Hermes-lite learnings are stored at: ${LEARNINGS_DIR}"
	echo "   Run a /hermes-reflect or /hermes-learn session first to create learnings."
	exit 0
fi

LEARNING_FILES=()
while IFS= read -r -d '' f; do
	LEARNING_FILES+=("$f")
done < <(find "${LEARNINGS_DIR}" -name '*.md' -type f -print0 2>/dev/null || true)

if [[ ${#LEARNING_FILES[@]} -eq 0 ]]; then
	echo "ℹ️  No .md files found in ${LEARNINGS_DIR}."
	echo "   Nothing to package."
	exit 0
fi

echo "Found ${#LEARNING_FILES[@]} learning file(s) in ${LEARNINGS_DIR}"
echo ""

# ─── Interactive confirmation ─────────────────────────────────────
if [[ "${MODE}" == "interactive" ]]; then
	if [[ ! -t 0 ]]; then
		echo "ERROR: no TTY available; refusing to run without --yes." >&2
		exit 1
	fi
	read -r -p "Package ${#LEARNING_FILES[@]} learnings into capsule? [y/N] " reply
	case "${reply}" in
	y | Y | yes | YES) : ;;
	*)
		echo "aborted."
		exit 0
		;;
	esac
fi

# ─── Generate capsule ─────────────────────────────────────────────
echo "==> Generating capsule..."

CAPSULE_CONTENT=""
CAPSULE_CONTENT+="# Hermes Learning Capsule\n\n"
CAPSULE_CONTENT+="> Generated by \`hermes-learning-capsule.sh\` on $(date '+%Y-%m-%d %H:%M:%S')\n"
CAPSULE_CONTENT+="> Source: ${LEARNINGS_DIR}\n"
CAPSULE_CONTENT+="> Total learnings: ${#LEARNING_FILES[@]}\n\n"
CAPSULE_CONTENT+="---\n\n"

for f in "${LEARNING_FILES[@]}"; do
	rel="${f#"${LEARNINGS_DIR}"/}"
	CAPSULE_CONTENT+="## ${rel}\n\n"
	CAPSULE_CONTENT+="$(cat "${f}" 2>/dev/null || echo "*[unreadable]*")\n"
	CAPSULE_CONTENT+="\n---\n\n"
done

CAPSULE_CONTENT+="*End of capsule — ${#LEARNING_FILES[@]} learnings packaged.*\n"

# ─── Write or stdout ─────────────────────────────────────────────-
if [[ -n "${OUTPUT_FILE}" ]]; then
	mkdir -p "$(dirname "${OUTPUT_FILE}")"
	printf "%b" "${CAPSULE_CONTENT}" >"${OUTPUT_FILE}"
	echo "✅ Capsule written to: ${OUTPUT_FILE}"
else
	printf "%b" "${CAPSULE_CONTENT}"
	echo ""
	echo "---"
	echo "📦 Capsule complete — ${#LEARNING_FILES[@]} learnings packaged."
fi
