#!/usr/bin/env bash
# ============================================================================
# sync-guard-bashrc.sh — regenerate templates/guard/opk-guard-bashrc
#
# The bashrc fragment embeds scripts/guard-rules.sh verbatim so it is
# self-contained when copied to $HOME/.config/opencode-power-kit/guard/.
# Run this after ANY change to guard-rules.sh. Freshness is enforced by
# scripts/test-command-guard.sh (generates via --stdout, diffs against the
# committed template).
#
# Usage:
#   sync-guard-bashrc.sh            # write templates/guard/opk-guard-bashrc
#   sync-guard-bashrc.sh --stdout   # print the fragment to stdout (read-only,
#                                   # never touches the repo — for tests)
# ============================================================================
set -euo pipefail

KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENGINE="$KIT_DIR/scripts/guard-rules.sh"
OUT="$KIT_DIR/templates/guard/opk-guard-bashrc"
OUT_TMP="$OUT.tmp"
STDOUT_MODE=0
[[ "${1:-}" == "--stdout" ]] && STDOUT_MODE=1

[[ -f "$ENGINE" ]] || { echo "sync-guard-bashrc: missing $ENGINE" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

{
  cat <<'EOF'
# ────────────────────────────────────────────────────────────────────────────
# opk-guard-bashrc — opencode-power-kit
#
# Guard Bash: blocks/warns dangerous shell commands BEFORE they execute
# (rm -rf, git reset --hard, git clean -f, git push --force/-f,
# curl|sh pipe-to-shell, SQL DROP/TRUNCATE/DELETE without WHERE,
# redirect/tee into sensitive files like .env, secrets, private keys).
#
# Setup:
#   1. Non-interactive (every bash child, incl. `opk run`/`opencode`
#      subprocesses) — add to ~/.bashrc or ~/.profile:
#        export BASH_ENV="$HOME/.config/opencode-power-kit/guard/opk-guard-bashrc"
#   2. Interactive (blocks typed commands before running them):
#        source "$HOME/.config/opencode-power-kit/guard/opk-guard-bashrc"
#
# Context variables:
#   OPK_GUARD_ROOT    project root used in messages (default: $PWD)
#   OPK_GUARD_SILENT  1 = suppress the reason text, verdict only
#
# This file is GENERATED by scripts/sync-guard-bashrc.sh — do not edit by
# hand; edit scripts/guard-rules.sh and re-run the generator.
# ────────────────────────────────────────────────────────────────────────────
EOF

  echo
  echo "# === GUARD-RULES ENGINE (generated from scripts/guard-rules.sh) ==="
  tail -n +2 "$ENGINE"   # strip the #! line; header comment stays
  echo "# === END ENGINE ==="
  echo

  cat <<'EOF'
# ─── DEBUG-trap glue: check BEFORE the command runs ────────────────────────
# When a dangerous command is detected, the trap prints BLOCKED to stderr
# and prevents execution.  Behavior differs by shell mode:
#
#   Non-interactive (bash -c, BASH_ENV subprocesses):
#     exit 1 — terminates the process with nonzero status.
#
#   Interactive (source into a live shell):
#     return 1 with extdebug — skips the current command; shell survives.
#     The next command typed by the user runs normally.
_opk_guard_debug() {
  # Re-entry guard: DEBUG fires for every simple command, including those
  # inside this very function; the local shadows the flag for nested traps.
  [[ "${_opk_guard_active:-0}" == "1" ]] && return 0
  local c="${BASH_COMMAND:-}"
  _opk_guard_active=1
  case "$c" in
    '' | _opk_guard_* | opk_guard_* | local* | unset* | return* | exit* | :* | '[['* | trap* | source* | shopt*)
      _opk_guard_active=0
      return 0 ;;
  esac
  if ! OPK_GUARD_SILENT=1 opk_guard_scan "$c" "${OPK_GUARD_ROOT:-$PWD}"; then
    echo "opk-guard: BLOCKED — $c (run it by hand if you are sure)" >&2
    _opk_guard_active=0
    if [[ "$-" == *i* ]]; then
      # Interactive shell: skip the command but keep the shell alive.
      shopt -s extdebug 2>/dev/null || true
      return 1
    else
      # Non-interactive: terminate the process with nonzero.
      exit 1
    fi
  fi
  _opk_guard_active=0
  return 0
}
trap '_opk_guard_debug' DEBUG
EOF
} > "$OUT_TMP"

if [[ $STDOUT_MODE -eq 1 ]]; then
	cat "$OUT_TMP"
	rm -f "$OUT_TMP"
else
	mv "$OUT_TMP" "$OUT"
	echo "sync-guard-bashrc: wrote $OUT"
fi
